// The module type for `import mark from "…/agentsmith-mark.png"`.
//
// next-env.d.ts declares it too, but that file is generated by `next build` and
// gitignored, and CI type-checks BEFORE it builds — so without this, `tsc`
// passes on any machine that has built once and fails in CI. It did, on the
// first push of these marks (.agent-rfc/designs/portal-brand.md).
/// <reference types="next/image-types/global" />
