apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onprem.fullname" . }}-prod
  labels:
    app.kubernetes.io/name: {{ include "onprem.fullname" . }}
    app.kubernetes.io/component: prod
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "onprem.fullname" . }}
      app.kubernetes.io/component: prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "onprem.fullname" . }}
        app.kubernetes.io/component: prod
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: app
          image: {{ .Values.image.prod }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.image.port }}
          {{- include "onprem.envFrom" . | nindent 10 }}
          env:
            {{- include "onprem.env" . | nindent 12 }}
          readinessProbe:
            httpGet: { path: /healthz, port: {{ .Values.image.port }} }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: {{ .Values.image.port }} }
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
