apiVersion: v1
kind: Service
metadata:
  name: {{ include "onprem.fullname" . }}-prod
spec:
  selector:
    app.kubernetes.io/name: {{ include "onprem.fullname" . }}
    app.kubernetes.io/component: prod
  ports:
    - port: {{ .Values.image.port }}
      targetPort: {{ .Values.image.port }}
---
{{- if .Values.canary.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "onprem.fullname" . }}-canary
spec:
  selector:
    app.kubernetes.io/name: {{ include "onprem.fullname" . }}
    app.kubernetes.io/component: canary
  ports:
    - port: {{ .Values.image.port }}
      targetPort: {{ .Values.image.port }}
{{- end }}
---
{{- if .Values.shadow.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "onprem.fullname" . }}-shadow
spec:
  selector:
    app.kubernetes.io/name: {{ include "onprem.fullname" . }}
    app.kubernetes.io/component: shadow
  ports:
    - port: {{ .Values.image.port }}
      targetPort: {{ .Values.image.port }}
{{- end }}
