"""
generate-ide-config.py — generates .cursorrules, CLAUDE.md, and Antigravity
skill files from templates/agent-rules.yaml, the single source of truth
(SPECS.md §4, §13, §22 Phase 5).

Called by the post-checkout hook instead of embedding IDE-rule content
inline — editing templates/agent-rules.yaml is now the only way to change
what gets written to .cursorrules / CLAUDE.md / .agents/skills/*/skill.md.

Idempotent: never overwrites an existing .cursorrules, CLAUDE.md, or
skill.md (same behavior as the hook's previous `[ ! -f ... ]` guards).

Usage:
    python3 generate-ide-config.py \\
        --repo-root /path/to/repo \\
        --rules-file /path/to/templates/agent-rules.yaml \\
        --stack ts-react|python-fastapi|go|generic \\
        --project-name myproject --owner-id me@example.com \\
        --otel-endpoint http://localhost:6006 --test-cmd "pytest" \\
        --framework-version 1.0.0
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any


def _load_rules(rules_file: Path) -> dict:
    try:
        import yaml  # type: ignore
    except ImportError:
        print(
            "❌ generate-ide-config.py requires pyyaml (pip install -r requirements.txt). "
            "IDE config was NOT regenerated.",
            file=sys.stderr,
        )
        sys.exit(1)
    with rules_file.open() as fh:
        return yaml.safe_load(fh) or {}


def _render_cursorrules(rules: dict, stack: str, ctx: dict[str, str]) -> str:
    lines = [
        "# AgentSmith — Agent Guardrails",
        f"# Project: {ctx['project_name']} | Owner: {ctx['owner_id']}",
        f"# Auto-generated by AgentSmith v{ctx['framework_version']} "
        f"from templates/agent-rules.yaml — do not edit this file directly.",
        "",
    ]

    pillar_titles = {
        1: "REQUIREMENTS & DESIGN",
        2: "BUILD ARCHITECTURE (Ponytail Rules)",
        3: "TRACING & EVALUATIONS",
        4: "TESTING GUARDRAILS",
        5: "OPERATIONS & SELF-IMPROVEMENT",
        6: "INTERFACE CONSTRAINTS (Caveman Compression)",
        7: "STACK-SPECIFIC RULES",
        8: "OBSERVABILITY WIRE",
        9: "MULTI-AGENT ORCHESTRATION",
        10: "COST-OPTIMISATION ROUTING",
    }

    for pillar in rules.get("pillars", []):
        pid = pillar["id"]
        title = pillar_titles.get(pid, pillar["name"].upper())
        rule_text = pillar["rule"].strip()
        # Substitute the same placeholders the old inline heredocs used.
        rule_text = (
            rule_text.replace("$AGENT_PHOENIX_ENDPOINT", ctx["otel_endpoint"])
            .replace("{{OWNER_ID}}", ctx["owner_id"])
            .replace("{{PROJECT_NAME}}", ctx["project_name"])
        )
        lines.append(f"## {pid}. {title}")
        lines.append(f"- {rule_text}")
        if pid == 3:
            lines.append(f"- OTel endpoint for this project: {ctx['otel_endpoint']}/v1/traces")
        if pid == 4:
            lines.append(f"- Test command for this project: {ctx['test_cmd']}")
        lines.append("")

    stack_def = (rules.get("stacks") or {}).get(stack)
    if stack_def:
        lines.append(f"## 11. {stack.upper()} ADDENDUM")
        for r in stack_def.get("additional_rules", []):
            lines.append(f"- {r}")
        lines.append("")

    return "\n".join(lines)


def _render_claude_md(ctx: dict[str, str]) -> str:
    return f"""# AgentSmith — Claude Code Instructions
# Project: {ctx['project_name']} | Owner: {ctx['owner_id']}
# Auto-generated from templates/agent-rules.yaml — do not edit this file directly.

## Compliance
Follow all rules in `.cursorrules` exactly. They are not suggestions.

## Session Start Checklist
1. Read `.agent-history.log` — surface any unresolved MAJOR/CRITICAL entries to the user.
2. Check `.agent-rfc/` — confirm a spec exists before touching any source file.
3. Query the Knowledge Graph: `python3 scripts/local_knowledge_graph.py` to identify dependencies.

## Test Command
```
{ctx['test_cmd']}
```

## Observability
- OTel endpoint: {ctx['otel_endpoint']}/v1/traces
- Emit spans for every tool call, LLM invocation, and file write.

## Output Format
Code only. No preambles. No summaries. No explanations outside inline comments.
"""


def _render_skill(skill: dict, rules: dict, ctx: dict[str, str]) -> str:
    pillar_by_id = {p["id"]: p for p in rules.get("pillars", [])}
    lines = [f"# {skill['title']}", "## Trigger", skill["trigger"], "", "## Instructions"]
    for pid in skill.get("pillars", []):
        pillar = pillar_by_id.get(pid)
        if not pillar:
            continue
        rule_text = pillar["rule"].strip().replace("$AGENT_PHOENIX_ENDPOINT", ctx["otel_endpoint"])
        lines.append(f"- ({pillar['name']}) {rule_text}")
    lines.append(f"- OTel endpoint: {ctx['otel_endpoint']}/v1/traces")
    lines.append(f"- Owner: {ctx['owner_id']} | Project: {ctx['project_name']}")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", required=True)
    ap.add_argument("--rules-file", required=True)
    ap.add_argument("--stack", default="generic")
    ap.add_argument("--project-name", required=True)
    ap.add_argument("--owner-id", required=True)
    ap.add_argument("--otel-endpoint", required=True)
    ap.add_argument("--test-cmd", default="echo 'No test command configured'")
    ap.add_argument("--framework-version", default="1.0.0")
    args = ap.parse_args()

    repo_root = Path(args.repo_root)
    rules_file = Path(args.rules_file)
    if not rules_file.exists():
        print(f"❌ Rules file not found: {rules_file}. IDE config was NOT regenerated.", file=sys.stderr)
        sys.exit(1)

    rules = _load_rules(rules_file)
    ctx = {
        "project_name": args.project_name,
        "owner_id": args.owner_id,
        "otel_endpoint": args.otel_endpoint,
        "test_cmd": args.test_cmd,
        "framework_version": args.framework_version,
    }

    cursorrules_path = repo_root / ".cursorrules"
    if not cursorrules_path.exists():
        cursorrules_path.write_text(_render_cursorrules(rules, args.stack, ctx))
        print(f"✅ Written .cursorrules ({len(rules.get('pillars', []))} pillars + {args.stack} addendum) from agent-rules.yaml")

    claude_md_path = repo_root / "CLAUDE.md"
    if not claude_md_path.exists():
        claude_md_path.write_text(_render_claude_md(ctx))
        print("✅ Written CLAUDE.md from agent-rules.yaml")

    for skill in rules.get("skills", []):
        skill_dir = repo_root / ".agents" / "skills" / skill["id"]
        skill_path = skill_dir / "skill.md"
        if not skill_path.exists():
            skill_dir.mkdir(parents=True, exist_ok=True)
            skill_path.write_text(_render_skill(skill, rules, ctx))

    if rules.get("skills"):
        print(f"✅ Written Antigravity skill files ({', '.join(s['id'] for s in rules['skills'])}) from agent-rules.yaml")


if __name__ == "__main__":
    main()
